"""add column target_type

Revision ID: 07e27e93ef0a
Revises: abe599d40ab6
Create Date: 2025-04-19 15:43:02.411860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e27e93ef0a'
down_revision: Union[str, None] = 'abe599d40ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('target_type', sa.String(length=1000), nullable=True))
    op.alter_column('profiles', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('profiles', 'target_type')
    # ### end Alembic commands ###
