"""re-add hobby as array enum

Revision ID: 543367a0a779
Revises: 4b4cca9b8bc0
Create Date: 2025-04-19 16:30:35.120774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543367a0a779'
down_revision: Union[str, None] = '4b4cca9b8bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('hobby', sa.ARRAY(sa.Enum('LISTENING_TO_MUSIC', 'SINGING', 'PLAYING_GUITAR', 'RUNNING', 'YOGA', 'READING', 'COOKING', 'PHOTOGRAPHY', 'TRAVELING', 'VIDEO_GAMES', 'DOG_LOVER', 'MEDITATION', 'FASHION', 'BLOGGING', name='hobbyenum')), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'hobby')
    # ### end Alembic commands ###
